biped_mech = {
    'left arm': [],
    'left arm (r)': [],
    'right arm': [],
    'right arm (r)': [],
    'left torso': [],
    'left torso (r)': [],
    'right torso': [],
    'right torso (r)': [],
    'center torso': [],
    'center torso (r)': [],
    'head': [],
    'head (r)': [],
    'left leg': [],
    'left leg (r)': [],
    'right leg': [],
    'right leg (r)': [],
    'none': [],
}

tripod_mech = {
    'left arm': [],
    'left arm (r)': [],
    'right arm': [],
    'right arm (r)': [],
    'left torso': [],
    'left torso (r)': [],
    'right torso': [],
    'right torso (r)': [],
    'center torso': [],
    'center torso (r)': [],
    'head': [],
    'head (r)': [],
    'left leg': [],
    'left leg (r)': [],
    'right leg': [],
    'right leg (r)': [],
    'center leg': [],
    'center leg (r)': [],
    'none': [],
}

quad_mech = {
    'right arm': [],
    'right arm (r)': [],
    'left arm': [],
    'left arm (r)': [],
    'left torso': [],
    'left torso (r)': [],
    'right torso': [],
    'right torso (r)': [],
    'center torso': [],
    'center torso (r)': [],
    'head': [],
    'head (r)': [],
    'front left leg': [],
    'front right leg': [],
    'rear left leg': [],
    'rear right leg': [],
    'front left leg (r)': [],
    'front right leg (r)': [],
    'rear left leg (r)': [],
    'rear right leg (r)': [],
    'none': [],
}

weapon_location_lookup = {'biped': biped_mech,
                          'biped omnimech': biped_mech,
                          'lam': biped_mech,
                          'tripod': tripod_mech,
                          'tripod omnimech': tripod_mech,
                          'tripod battlemech': tripod_mech,
                          'quad omnimech': quad_mech,
                          'quad': quad_mech,
                          'quadvee': quad_mech,
                          'quadvee omnimech': quad_mech,
                          }
