equipment_alias = {
    "isantipersonnelpod": "apod",
    "clantipersonnelpod": "apod",
    "isapod": "apod",
    "clapod": "apod",
    "isbpod": "bpod",
    "clbpod": "bpod",
    "ismpod": "mpod",
    "m-pod": "mpod",
    "clmpod": "mpod",
    "b-pod" : "b-pod",
    "anti-battlearmorpods(b-pods)": "b-pod",
    "isams": "ams",
    "ams": "ams",
    "anti-missilesystem": "ams",
    "clams": "ams",
    "isantimissilesystem": "ams",
    "anti-misslesystem": "ams",
    "clantimissilesystem": "ams",
    "clantimissilesys": "ams",
    "cllaserantimissilesys": "lams",
    "islaserams": "lams",
    "cllaserams": "lams",
    "islaserantimissilesystem": "lams",
    "laserams": "lams",
    "cllaserantimissilesystem": "lams",
    "isartemisiv": "aiv",
    "clartemisiv": "aiv",
    "clartemisv": "av",
    "isartemisv": "av",
    "isapollo": "apollo",
    "isaes": "aes",
    "isbeagleactiveprobe": "probe",
    "isbloodhoundactiveprobe": "bhprobe",
    "clactiveprobe": "cprobe",
    "islightprobe": "lprobe",
    "islightactiveprobe": "lprobe",
    "cllightprobe": "clprobe",
    "cllightactiveprobe": "clprobe",
    "isc3mastercomputer": "c3m",
    "c3computer[master]": "c3m",
    "c3computer(master)": "c3m",
    "isc3masterunit": "c3m",
    "isc3master": "c3m",
    "isc3slavecomputer": "c3s",
    "isc3slaveunit": "c3s",
    "isc3slave": "c3s",
    "isc3masterboosteddystemunit": "c3bm",
    "isc3boostedsystemslave": "c3bs",
    "isc3boostedsystemslaveunit": "c3bs",
    "c3masterwithtage" : "c3mt",
    "isc3iunit": "c3i",
    "isimprovedc3cpu": "c3i",
    "isc3icomputer": "c3i",
    "isc3remotesensorlauncher" : "c3rs",
    "c3remotesensorlauncher": "c3rs",
    "isremotesensordispenser" : "c3rs",
    "isremotsensordispenser": "c3rs",
    "c3masterboostedwithtag": "c3bmt",
    "c3masterwithtag" : "c3mt",
    "iscase": "case",
    "clcase": "case",
    "iscaseii": "case2",
    "clcaseii": "case2",
    "isecm": "ecm",
    "clecm": "cecm",
    "isguardianecmsuite": "ecm",
    "isguardianecm": "ecm",
    "isecmsuite": "ecm",
    "clecmsuite": "cecm",
    "isangelecmsuite": "aecm",
    "clangelecmsuite": "aecm",
    "isangelecm": "aecm",
    "clangelecm": "aecm",
    "isjumpjet": "jump",
    "cljumpjet": "jump",
    "improvedjumpjet": "ijump",
    "isimprovedjumpjet": "ijump",
    "climprovedjumpjet": "ijump",
    "ismasc": "masc",
    "clmasc": "masc",
    "istag": "tag",
    "cltag": "tag",
    "clantag" : "tag",
    "tag": "tag",
    "tag(clan)": "tag",
    "islighttag": "ltag",
    "cllighttag": "ltag",
    "lighttag[clan]" : 'ltag',
    "lighttag": "ltag",
    "clanlighttag" : "ltag",
    "istargetingcomputer": "tc",
    "cltargetingcomputer": "tc",
    "istsm": "tsm",
    "cltsm": "tsm",
    "istriplestrengthmyomer": "tsm",
    "cltriplestrengthmyomer": "tsm",
    "issupercharger": "supercharger",
    "clsupercharger": "supercharger",
    "clwatchdogecmsuite": "cews",
    "heavydutygyro": "hdgyro",
    "ispartialwing": "partwing",
    "clpartialwing": "partwing",
    "iscoolantpod": "cpod",
    "clcoolantpod": "cpod",
    "isppccapacitor": "ppccapacitor",
    "clppccapacitor": "ppccapacitor",
    "fullheadejectionsystem": "fhes",
    "smallcockpit": "smcp",
    "torsomountedcockpit": "tmcp",
    "isumu": "umu",
    "clumu": "umu",
    "ismechanicaljumpbooster": "mechjumpbooster",
    "clmechanicaljumpbooster": "mechjumpbooster",
    "isquadturret": "turret",
    "clquadturret": "turret",
    "isheadturret": "turret",
    "clheadturret": "turret",
    "isshoulderturret": "turret",
    "clshoulderturret": "turret",
    "searchlight": "searchlight",
    "lifthoist": "lifthoist",
    "islifthoist": "lifthoist",
    "cargo(0.5tons)": "cargo",
    "cargo(1ton)": "cargo",
    "riscadvancedpointdefensesystem": "rapds",
    "ischaffpod": "chaffpod",

    "ismass" : "mass",


    # CV Equipment
    "troopspace": "troopspace",
    "TroopSpace": "troopspace",

    # BA Equipment:

    "isbaturret": "turret",
    "clbaturret": "turret",
    "isdetachableweaponpack": "dwp",
    "cldetachableweaponpack": "dwp",
    "isbajumpbooster": "jumpbooster",
    "clbajumpbooster": "jumpbooster",
    "isbamechanicaljumpbooster": "jumpbooster",
    "clbamechanicaljumpbooster": "jumpbooster",
    "isbapartialwing": "partwing",
    "clbapartialwing": "partwing",
    "isbalprobe": "lprobe",
    "clbalprobe": "lprobe",
    "isbalighttag": "ltag",
    "clbalighttag": "ltag",
    "isbaapds": "apds",
    "clbaapds": "apds",
    "clbamyomerbooster": "myomerboost",
    "clbamb": "myomerboost",
    "isbaecm": "ecm",
    "clbaecm": "cecm",
    "isbaguardianecmsuite": "ecm",
    "isbaguardianecm": "ecm",
    "isbaecmsuite": "ecm",
    "clbaecmsuite": "cecm",
    "isbaangelecmsuite": "aecm",
    "clbaangelecmsuite": "aecm",
    "isbaangelecm": "aecm",
    "clbaangelecm": "aecm",
    "isbasinglehexecm": "ecm",
    "clbasinglehexecm": "cecm",
    "isbac3": "c3s",
    "isbc3": "c3s",
    "isbac3i": "c3i",
    "isbc3i": "c3i"
};
