biped_mech = {
    'la': 'left arm',
    'ra': 'right arm',
    'lt': 'left torso',
    'rt': 'right torso',
    'ct': 'center torso',
    'hd': 'head',
    'll': 'left leg',
    'rl': 'right leg',
    'rtl': 'rear left torso',
    'rtr': 'rear right torso',
    'rtc': 'rear center torso',
}

tripod_mech = {
    'la': 'left arm',
    'ra': 'right arm',
    'lt': 'left torso',
    'rt': 'right torso',
    'ct': 'center torso',
    'hd': 'head',
    'll': 'left leg',
    'rl': 'right leg',
    'cl': 'center leg',
    'rtl': 'rear left torso',
    'rtr': 'rear right torso',
    'rtc': 'rear center torso',
}

quad_mech = {
    'la': 'left arm',
    'ra': 'right arm',
    'fll': 'front left leg',
    'frl': 'front right leg',
    'rll': 'rear left leg',
    'rrl': 'rear right leg',
    'lt': 'left torso',
    'rt': 'right torso',
    'ct': 'center torso',
    'hd': 'head',
    'll': 'left leg',
    'rl': 'right leg',
    'cl': 'center leg',
    'rtl': 'rear left torso',
    'rtr': 'rear right torso',
    'rtc': 'rear center torso',
}

equip_config_lookup = {'biped': biped_mech,
                       'biped omnimech': biped_mech,
                       'lam': biped_mech,
                       'tripod': tripod_mech,
                       'tripod omnimech': tripod_mech,
                       'tripod battlemech': tripod_mech,
                       'quad omnimech': quad_mech,
                       'quad': quad_mech,
                       'quadvee': quad_mech,
                       'quadvee omnimech': quad_mech,
                       }
